# Generated by Django 5.2.7 on 2025-10-09 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(db_column='CategoriaId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
                ('estado', models.BooleanField(db_column='Estado', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categorias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('empresa_id', models.AutoField(db_column='EmpresaId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('rut', models.CharField(db_column='RUT', max_length=12, unique=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=15, null=True)),
                ('email', models.EmailField(db_column='Email', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('estado', models.BooleanField(db_column='Estado', default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.AutoField(db_column='PedidoId', primary_key=True, serialize=False)),
                ('numero_pedido', models.CharField(db_column='NumeroPedido', max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_column='FechaHora')),
                ('estado', models.CharField(db_column='Estado', max_length=20)),
                ('tipo_venta', models.CharField(db_column='TipoVenta', max_length=20)),
                ('es_offline', models.BooleanField(db_column='EsOffline', default=False)),
                ('fecha_sincronizacion', models.DateTimeField(blank=True, db_column='FechaSincronizacion', null=True)),
                ('total_bruto', models.DecimalField(db_column='TotalBruto', decimal_places=2, max_digits=12)),
                ('descuento_total', models.DecimalField(db_column='DescuentoTotal', decimal_places=2, default=0, max_digits=12)),
                ('iva', models.DecimalField(db_column='IVA', decimal_places=2, default=0, max_digits=12)),
                ('total_neto', models.DecimalField(db_column='TotalNeto', decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'PEDIDOS',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('metodo_pago_id', models.AutoField(db_column='MetodoPagoId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('tipo', models.CharField(db_column='Tipo', max_length=20)),
                ('estado', models.BooleanField(db_column='Estado', default=True)),
                ('empresa', models.ForeignKey(db_column='EmpresaId', on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'METODOSPAGO',
            },
        ),
        migrations.CreateModel(
            name='Modificador',
            fields=[
                ('modificador_id', models.AutoField(db_column='ModificadorId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('tipo', models.CharField(db_column='Tipo', max_length=50)),
                ('valor_adicional', models.DecimalField(db_column='ValorAdicional', decimal_places=2, default=0, max_digits=10)),
                ('estado', models.BooleanField(db_column='Estado', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('empresa', models.ForeignKey(db_column='EmpresaId', on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'verbose_name': 'Modificador',
                'verbose_name_plural': 'Modificadores',
                'db_table': 'Modificadores',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pago_id', models.AutoField(db_column='PagoId', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(db_column='Monto', decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, db_column='Referencia', max_length=100, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_column='FechaHora')),
                ('pos_id', models.CharField(blank=True, db_column='PosId', max_length=50, null=True)),
                ('metodo_pago', models.ForeignKey(db_column='MetodoPagoId', on_delete=django.db.models.deletion.CASCADE, to='core.metodopago')),
                ('pedido', models.ForeignKey(db_column='PedidoId', on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'PAGOS',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('boleta_id', models.AutoField(db_column='BoletaId', primary_key=True, serialize=False)),
                ('folio', models.BigIntegerField(db_column='Folio', unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, db_column='FechaEmision')),
                ('rut_cliente', models.CharField(blank=True, db_column='RUTCliente', max_length=12, null=True)),
                ('monto_total', models.DecimalField(db_column='MontoTotal', decimal_places=2, max_digits=12)),
                ('codigo_qr', models.CharField(blank=True, db_column='CodigoQR', max_length=500, null=True)),
                ('estado_envio_sii', models.CharField(blank=True, db_column='EstadoEnvioSII', max_length=20, null=True)),
                ('xml_boleta', models.TextField(blank=True, db_column='XMLBoleta', null=True)),
                ('url_pdf', models.CharField(blank=True, db_column='URLPDF', max_length=300, null=True)),
                ('pedido', models.ForeignKey(db_column='PedidoId', on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
            ],
            options={
                'verbose_name': 'Boleta',
                'verbose_name_plural': 'Boletas',
                'db_table': 'BOLETAS',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(db_column='ProductoId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
                ('precio_base', models.DecimalField(db_column='PrecioBase', decimal_places=2, max_digits=10)),
                ('tiempo_preparacion', models.IntegerField(db_column='TiempoPreparacion')),
                ('estado', models.BooleanField(db_column='Estado', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('categoria', models.ForeignKey(db_column='CategoriaId', on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'PRODUCTOS',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('detalle_id', models.AutoField(db_column='DetalleId', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('precio_unitario', models.DecimalField(db_column='PrecioUnitario', decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(db_column='Descuento', decimal_places=2, default=0, max_digits=10)),
                ('total_linea', models.DecimalField(db_column='TotalLinea', decimal_places=2, max_digits=12)),
                ('notas', models.CharField(blank=True, db_column='Notas', max_length=200, null=True)),
                ('pedido', models.ForeignKey(db_column='PedidoId', on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
                ('producto', models.ForeignKey(db_column='ProductoId', on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
                'db_table': 'PEDIDODETALLES',
            },
        ),
        migrations.CreateModel(
            name='ReglaNegocio',
            fields=[
                ('regla_id', models.AutoField(db_column='ReglaId', primary_key=True, serialize=False)),
                ('tipo_regla', models.CharField(db_column='TipoRegla', max_length=20)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
                ('accion_modificador', models.ForeignKey(db_column='AccionModificadorId', on_delete=django.db.models.deletion.CASCADE, related_name='reglas_accion', to='core.modificador')),
                ('condicion_modificador', models.ForeignKey(db_column='CondicionModificadorId', on_delete=django.db.models.deletion.CASCADE, related_name='reglas_condicion', to='core.modificador')),
                ('producto', models.ForeignKey(db_column='ProductoId', on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
            options={
                'verbose_name': 'Regla de Negocio',
                'verbose_name_plural': 'Reglas de Negocio',
                'db_table': 'REGLASNEGOCIOS',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.AutoField(db_column='RolId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('empresa', models.ForeignKey(db_column='EmpresaId', on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'Roles',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('sucursal_id', models.AutoField(db_column='SucursalId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=15, null=True)),
                ('estado', models.BooleanField(db_column='Estado', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('empresa', models.ForeignKey(db_column='EmpresaId', on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'Sucursales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='sucursal',
            field=models.ForeignKey(db_column='SucursalId', on_delete=django.db.models.deletion.CASCADE, to='core.sucursal'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='sucursal',
            field=models.ForeignKey(db_column='SucursalId', on_delete=django.db.models.deletion.CASCADE, to='core.sucursal'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(db_column='UsuarioId', primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(db_column='Nombre', max_length=100)),
                ('email', models.EmailField(db_column='Email', max_length=100, unique=True)),
                ('contrasena_hash', models.CharField(db_column='ContrasenaHash', max_length=128)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=15, null=True)),
                ('estado', models.BooleanField(db_column='Estado', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('empresa', models.ForeignKey(db_column='EmpresaId', on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('rol', models.ForeignKey(db_column='RolId', on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
                ('sucursal', models.ForeignKey(db_column='SucursalId', on_delete=django.db.models.deletion.CASCADE, to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(db_column='UsuarioId', on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('cierre_id', models.AutoField(db_column='CierreId', primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateTimeField(db_column='FechaApertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, db_column='FechaCierre', null=True)),
                ('monto_inicial', models.DecimalField(db_column='MontoInicial', decimal_places=2, default=0, max_digits=12)),
                ('ingresos_efectivo', models.DecimalField(db_column='IngresosEfectivo', decimal_places=2, default=0, max_digits=12)),
                ('ingresos_electronicos', models.DecimalField(db_column='IngresosElectronicos', decimal_places=2, default=0, max_digits=12)),
                ('total_esperado', models.DecimalField(db_column='TotalEsperado', decimal_places=2, default=0, max_digits=12)),
                ('total_real', models.DecimalField(db_column='TotalReal', decimal_places=2, default=0, max_digits=12)),
                ('diferencia', models.DecimalField(db_column='Diferencia', decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(db_column='Estado', max_length=20)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=300, null=True)),
                ('sucursal', models.ForeignKey(db_column='SucursalId', on_delete=django.db.models.deletion.CASCADE, to='core.sucursal')),
                ('usuario', models.ForeignKey(db_column='UsuarioId', on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'db_table': 'CIERRESCAJA',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('auditoria_id', models.AutoField(db_column='AuditoriaId', primary_key=True, serialize=False)),
                ('accion', models.CharField(db_column='Accion', max_length=50)),
                ('entidad', models.CharField(db_column='Entidad', max_length=50)),
                ('entidad_id', models.IntegerField(db_column='EntidadId')),
                ('detalles', models.TextField(blank=True, db_column='Detalles', null=True)),
                ('ip', models.CharField(blank=True, db_column='IP', max_length=45, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_column='FechaHora')),
                ('sucursal', models.ForeignKey(db_column='SucursalId', on_delete=django.db.models.deletion.CASCADE, to='core.sucursal')),
                ('usuario', models.ForeignKey(db_column='UsuarioId', on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'db_table': 'AUDITORIA',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='PedidoDetalleModificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_aplicado', models.DecimalField(db_column='ValorAplicado', decimal_places=2, default=0, max_digits=10)),
                ('es_gratuito', models.BooleanField(db_column='EsGratuito', default=False)),
                ('detalle', models.ForeignKey(db_column='DetalleId', on_delete=django.db.models.deletion.CASCADE, to='core.pedidodetalle')),
                ('modificador', models.ForeignKey(db_column='ModificadorId', on_delete=django.db.models.deletion.CASCADE, to='core.modificador')),
            ],
            options={
                'verbose_name': 'Modificador de Detalle de Pedido',
                'verbose_name_plural': 'Modificadores de Detalles de Pedido',
                'db_table': 'PEDIDODETALLEMODIFICADORES',
                'unique_together': {('detalle', 'modificador')},
            },
        ),
        migrations.CreateModel(
            name='ProductoModificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_obligatorio', models.BooleanField(db_column='EsObligatorio', default=False)),
                ('modificador', models.ForeignKey(db_column='ModificadorId', on_delete=django.db.models.deletion.CASCADE, to='core.modificador')),
                ('producto', models.ForeignKey(db_column='ProductoId', on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
            options={
                'verbose_name': 'Producto Modificador',
                'verbose_name_plural': 'Producto Modificadores',
                'db_table': 'ProductoModificadores',
                'unique_together': {('producto', 'modificador')},
            },
        ),
    ]
