# Generated by Django 5.2.7 on 2025-10-09 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_empresa_alter_usuario_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='EmpresaId', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
    ]
