# Generated by Django 5.2.7 on 2025-10-18 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_rol_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, db_column='CategoriaId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria'),
        ),
    ]
