# Generated by Django 5.2.7 on 2025-10-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.CharField(blank=True, db_column='ImagenURL', max_length=500, null=True),
        ),
    ]
