# Generated by Django 5.2.7 on 2025-11-15 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_producto_imagen_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSucursal',
            fields=[
                ('usuario_sucursal_id', models.AutoField(db_column='UsuarioSucursalId', primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, db_column='FechaAsignacion')),
                ('estado', models.BooleanField(db_column='Estado', default=True)),
            ],
            options={
                'verbose_name': 'Usuario-Sucursal',
                'verbose_name_plural': 'Usuarios-Sucursales',
                'db_table': 'UsuariosSucursales',
                'managed': False,
            },
        ),

        # ❌ ESTA PARTE SE ELIMINA
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='sucursal',
        # ),

        migrations.CreateModel(
            name='TransaccionWebpay',
            fields=[
                ('transaccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=200)),
                ('buy_order', models.CharField(max_length=100)),
                ('session_id', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
            ],
            options={
                'db_table': 'TransaccionesWebpay',
            },
        ),
    ]
