"""
Django settings for settings project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import datetime
from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient
from azure.identity import DefaultAzureCredential

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!9ax_%z+v69y23rn@sg_j+ez!te4dhw7r(76(zoxq*1-bl!bdk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '20.172.13.183',
    'http://foodtrucksapp.cl',
    'https://foodtrucksapp.cl',
    'http://www.foodtrucksapp.cl',
    'https://www.foodtrucksapp.cl',
    'foodtrucksapp.cl',
    'www.foodtrucksapp.cl',
]


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'core',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'drf_spectacular_sidecar',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'core.authentication.CustomJWTAuthentication', 
        'rest_framework.authentication.BasicAuthentication', 
    ),
}


SPECTACULAR_SETTINGS = {
    'TITLE': 'FoodTruck API',
    'DESCRIPTION': 'API para gestión de empresa, sucursales, productos, pedidos, pagos y auditoría de la FoodTruckApp.',
    'VERSION': '1.0.0',

    'SERVE_INCLUDE_SCHEMA': False,

    'SECURITY': [
        {'BearerAuth': []}
    ],

    'COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            },
            'basicAuth': {
                'type': 'http',
                'scheme': 'basic'
            },
        }
    },

    'SERVE_AUTHENTICATION': [
        'rest_framework.authentication.BasicAuthentication',
    ],

    'SWAGGER_UI_SETTINGS': {
        "persistAuthorization": True,
        "requestInterceptor": "function(req) { return req; }",
        "responseInterceptor": """
            function(res) {
                try {
                    if (res && res.url && res.url.includes('/api/v1/auth/login/') && res.status === 200) {
                        const data = JSON.parse(res.data);
                        if (data.access) {
                            window.ui.preauthorizeApiKey('BearerAuth', data.access);
                            console.log('✔ JWT asignado automáticamente en Swagger (BearerAuth).');
                        }
                    }
                } catch (e) {
                    console.error('⚠️ Error procesando token JWT:', e);
                }
                return res;
            }
        """,
    },
}

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'settings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'settings.wsgi.application'


# ============================================================
# 🔐 CONFIGURACIÓN AZURE KEY VAULT (DB + WEBPAY)
# ============================================================
from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient

KEY_VAULT_URL = "https://keysfoodtruckapp.vault.azure.net/"

DB_PASSWORD = ""
WEBPAY_COMMERCE_CODE = None
WEBPAY_API_KEY = None
WEBPAY_URL = "https://webpay3gint.transbank.cl"

try:
    credential = DefaultAzureCredential()
    client = SecretClient(vault_url=KEY_VAULT_URL, credential=credential)

    # --- 🔑 DB Password ---
    DB_PASSWORD = client.get_secret("dbpassword").value

    # --- 💳 Webpay credentials ---
    WEBPAY_COMMERCE_CODE = client.get_secret("webpay-commerce-code").value
    WEBPAY_API_KEY = client.get_secret("webpay-api-key").value

except Exception as e:
    print("⚠️ No se pudieron obtener secretos desde Key Vault:", e)
    # Fallbacks útiles en desarrollo local
    DB_PASSWORD = os.getenv("DB_PASSWORD", "")
    WEBPAY_COMMERCE_CODE = os.getenv("WEBPAY_COMMERCE_CODE", "")
    WEBPAY_API_KEY = os.getenv("WEBPAY_API_KEY", "")

DATABASES = {
    'default': {
        'ENGINE': 'mssql', 
        'NAME': 'bdfoodtruck',
        'USER': 'vincent',
        'PASSWORD': DB_PASSWORD,
        'HOST': 'appfoodtruck.database.windows.net',
        'PORT': '',
        'CONN_MAX_AGE': 60,
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'encrypt': True,
            'trust_server_certificate': False,
            'connection_timeout': 15,
            'timeout': 30,
        },
    }
}


# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Autenticación
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/home/'
LOGOUT_REDIRECT_URL = '/login/'

# Configuración de JWT

JWT_SECRET_KEY = "9RS05stB0N1lcsb77L2POJV2SDNi5Oz-5NqwycNme3U0E0MRxHOh72Cl4fOkuNFyoFNJ4RTweUPyGAcnmCnZCA"
JWT_ALGORITHM = 'HS256' # Algoritmo de firma
JWT_ACCESS_TTL = datetime.timedelta(minutes=60) # Token válido por 60 minutos
JWT_REFRESH_TTL = datetime.timedelta(days=7) # Refresh token válido por 7 días

# Configuración Blob Storage
AZURE_BLOB_ACCOUNT_URL = "https://imagenesappfoodtruck.blob.core.windows.net"
AZURE_BLOB_CONTAINER   = "imagenes"
AZURE_DEFAULT_CREDENTIAL = DefaultAzureCredential()
MAX_UPLOAD_MB = 100  # Tamaño máximo de subida de imágenes en MB