from django.contrib import admin
from django.urls import path
from core import views
from django.views.generic import RedirectView
from core.views import producto_detail, productos_list , sucursales_list, sucursal_detail, empresas_list, empresa_detail, categorias_list, categoria_detail, roles_list, rol_detail, usuarios_list, usuario_detail, producto_imagen, modificadores_list, modificador_detail, producto_modificadores, regla_detail, reglas_list, metodos_pago_list, metodo_pago_detail, pedido_detail, pedidos_list, pedido_detalle_detail, pedido_detalles_list, detalle_modificador_detail, detalle_modificadores_list, pago_detail, pagos_list, boleta_detail, boletas_list, usuario_sucursal_detail, usuarios_sucursales_list, webpay_init, webpay_transaccion_detail, webpay_transacciones_list, webpay_commit, auditoria_detail, auditorias_list, cierre_caja_detail, cierres_caja_list
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
    SpectacularRedocView,
)


urlpatterns = [
    path('api/v1/auth/login/', views.login_api, name='api_login'),
    path('api/v1/auth/refresh/', views.refresh_api, name='api_refresh'),
    path('api/v1/auth/logout/', views.logout_api, name='api_logout'),
    path('api/v1/auth/me/', views.me_api, name='api_me'),
    path('api/v1/productos/<int:producto_id>/', producto_detail, name='producto_detail'),
    path("api/v1/productos/<int:producto_id>/imagen/", producto_imagen, name="producto-imagen"),
    path("api/v1/productos/", productos_list, name="productos-list"),
    path('api/v1/sucursales/', sucursales_list, name='sucursales_list'),
    path('api/v1/sucursales/<int:sucursal_id>/', sucursal_detail, name='sucursal_detail'),
    path('api/v1/empresas/', empresas_list, name='empresas_list'),
    path('api/v1/empresas/<int:empresa_id>/', empresa_detail, name='empresa_detail'),
    path('api/v1/categorias/', categorias_list, name='categorias_list'),
    path('api/v1/categorias/<int:categoria_id>/', categoria_detail, name='categoria_detail'),
    path('api/v1/roles/', roles_list, name='roles_list'),
    path('api/v1/roles/<int:rol_id>/', rol_detail, name='rol_detail'),
    path('api/v1/usuarios/', usuarios_list, name='usuarios_list'),
    path('api/v1/usuarios/<int:usuario_id>/', usuario_detail, name='usuario_detail'),
    path('api/v1/modificadores/', views.modificadores_list, name='modificadores_list'),
    path('api/v1/modificadores/<int:modificador_id>/', views.modificador_detail, name='modificador_detail'),
    path("api/v1/productos/<int:producto_id>/modificadores/", views.producto_modificadores, name="producto_modificadores"),
    path('api/v1/reglas-negocio/', reglas_list, name='reglas_list'),
    path('api/v1/reglas-negocio/<int:regla_id>/', regla_detail, name='regla_detail'),
    path('api/v1/metodos-pago/', metodos_pago_list, name='metodos_pago_list'),
    path('api/v1/metodos-pago/<int:metodo_pago_id>/', metodo_pago_detail, name='metodo_pago_detail'),
    path("api/v1/pedidos/", pedidos_list, name="pedidos_list"),
    path("api/v1/pedidos/<int:pedido_id>/", pedido_detail, name="pedido_detail"),
    path("api/v1/pedidos/<int:pedido_id>/detalles/", pedido_detalles_list),
    path("api/v1/pedidos/detalles/<int:detalle_id>/", pedido_detalle_detail),
    path("api/v1/pedidos/detalles/<int:detalle_id>/modificadores/", detalle_modificadores_list),
    path("api/v1/detalles-modificadores/<int:detalle_id>/<int:modificador_id>/", detalle_modificador_detail),
    path('api/v1/pagos/', pagos_list, name='pagos_list'),
    path('api/v1/pagos/<int:pago_id>/', pago_detail, name='pago_detail'),
    path('api/v1/boletas/', boletas_list, name='boletas_list'),
    path('api/v1/boletas/<int:boleta_id>/', boleta_detail, name='boleta_detail'),
    path("api/v1/usuarios-sucursales/", usuarios_sucursales_list, name="usuarios_sucursales_list"),
    path("api/v1/usuarios-sucursales/<int:usuario_sucursal_id>/", usuario_sucursal_detail, name="usuario_sucursal_detail"),
    path("api/v1/webpay/init/", views.webpay_init, name="webpay-init"),
    path("api/v1/webpay/transacciones/", webpay_transacciones_list),
    path("api/v1/webpay/transacciones/<int:transaccion_id>/", webpay_transaccion_detail),
    path("api/v1/webpay/commit/", views.webpay_commit, name="webpay_commit"),
    path("api/v1/auditorias/", auditorias_list),
    path("api/v1/auditorias/<int:auditoria_id>/", auditoria_detail),
    path("api/v1/cierres-caja/", cierres_caja_list),
    path("api/v1/cierres-caja/<int:cierre_id>/", cierre_caja_detail),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/docs/',
        SpectacularSwaggerView.as_view(url_name='schema'),
        name='swagger-ui',
    ),
    path(
        'api/redoc/',
        SpectacularRedocView.as_view(url_name='schema'),
        name='redoc',
    ),
]
