export const initialFoodTrucks = [
  {
    id: 'ft-001',
    name: 'La Callejera Burgers',
    location: 'Plaza Central',
    status: 'Operativo',
    lastSync: 'Hace 5 minutos',
    metrics: {
      salesThisMonth: 12500000,
      ordersInQueue: 12,
      satisfaction: 4.7,
      averageTicket: 5600,
    },
    categories: ['Hamburguesas', 'Acompanamientos', 'Bebidas'],
    products: [
      {
        id: 'prd-001',
        name: 'Burger Clasica',
        price: 5600,
        category: 'Hamburguesas',
        status: 'Disponible',
        stock: 45,
      },
      {
        id: 'prd-002',
        name: 'Burger Veggie',
        price: 5900,
        category: 'Hamburguesas',
        status: 'Disponible',
        stock: 30,
      },
      {
        id: 'prd-003',
        name: 'Papas Rusticas',
        price: 2500,
        category: 'Acompanamientos',
        status: 'Disponible',
        stock: 75,
      },
    ],
    staff: [
      {
        id: 'stf-001',
        name: 'Ana Torres',
        role: 'Vendedora',
        phone: '+56 9 1234 5678',
        shiftStart: '10:00',
        shiftEnd: '18:00',
        days: ['Lun', 'Mar', 'Mie', 'Jue', 'Vie'],
      },
      {
        id: 'stf-002',
        name: 'Matias Pardo',
        role: 'Cocinero',
        phone: '+56 9 9876 5432',
        shiftStart: '11:00',
        shiftEnd: '19:00',
        days: ['Lun', 'Mar', 'Mie', 'Jue', 'Vie'],
      },
    ],
  },
  {
    id: 'ft-002',
    name: 'Ruta del Sabor',
    location: 'Costanera Sur',
    status: 'Operativo',
    lastSync: 'Hace 2 horas',
    metrics: {
      salesThisMonth: 9800000,
      ordersInQueue: 5,
      satisfaction: 4.5,
      averageTicket: 4800,
    },
    categories: ['Completos', 'Empanadas', 'Bebestibles'],
    products: [
      {
        id: 'prd-101',
        name: 'Completo Italiano',
        price: 3500,
        category: 'Completos',
        status: 'Disponible',
        stock: 60,
      },
      {
        id: 'prd-102',
        name: 'Empanada Queso',
        price: 1800,
        category: 'Empanadas',
        status: 'Disponible',
        stock: 120,
      },
      {
        id: 'prd-103',
        name: 'Limonada Menta',
        price: 2200,
        category: 'Bebestibles',
        status: 'Agotado',
        stock: 0,
      },
    ],
    staff: [
      {
        id: 'stf-101',
        name: 'Carla Gutierrez',
        role: 'Supervisora',
        phone: '+56 9 4567 8910',
        shiftStart: '09:00',
        shiftEnd: '17:00',
        days: ['Lun', 'Mar', 'Jue', 'Vie'],
      },
      {
        id: 'stf-102',
        name: 'Pedro Sanhueza',
        role: 'Maestro Cocina',
        phone: '+56 9 7654 3201',
        shiftStart: '12:00',
        shiftEnd: '20:00',
        days: ['Mie', 'Jue', 'Vie', 'Sab'],
      },
    ],
  },
  {
    id: 'ft-003',
    name: 'La Dulceria Movil',
    location: 'Parque Oriente',
    status: 'En Mantencion',
    lastSync: 'Ayer',
    metrics: {
      salesThisMonth: 4300000,
      ordersInQueue: 0,
      satisfaction: 4.9,
      averageTicket: 3200,
    },
    categories: ['Postres', 'Cafe', 'Bebidas Frias'],
    products: [
      {
        id: 'prd-201',
        name: 'Brownie Nuez',
        price: 2100,
        category: 'Postres',
        status: 'Disponible',
        stock: 20,
      },
      {
        id: 'prd-202',
        name: 'Cheesecake Frutos',
        price: 2600,
        category: 'Postres',
        status: 'Disponible',
        stock: 15,
      },
      {
        id: 'prd-203',
        name: 'Cold Brew',
        price: 2000,
        category: 'Cafe',
        status: 'Disponible',
        stock: 40,
      },
    ],
    staff: [
      {
        id: 'stf-201',
        name: 'Rocio Mendez',
        role: 'Encargada',
        phone: '+56 9 1111 2222',
        shiftStart: '08:00',
        shiftEnd: '16:00',
        days: ['Mie', 'Jue', 'Vie', 'Sab', 'Dom'],
      },
    ],
  },
];

export const supervisorProfiles = [
  {
    id: 'sup-001',
    name: 'Carla Gutierrez',
    email: 'carla@rutadelsabor.cl',
    phone: '+56 9 4567 8910',
    foodTruckId: 'ft-002',
    permissions: {
      canEditProducts: true,
      canEditSchedules: true,
    },
  },
  {
    id: 'sup-002',
    name: 'Rocio Mendez',
    email: 'rocio@dulceria.cl',
    phone: '+56 9 1111 2222',
    foodTruckId: 'ft-003',
    permissions: {
      canEditProducts: true,
      canEditSchedules: false,
    },
  },
];
